sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Prodyot-dutta/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Prodyot-dutta/docker-react npm run test -- --coverage

Deploy:
  - deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "Frontend"
    env: "Frontend-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-986006681813"
    bucket_path: "Frontend"
    on:
    branch: main
